# Generated by Django 4.2.24 on 2025-11-10 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comunas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comuna', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadosPropiedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperacionesPropiedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacion', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TiposPropiedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoPropiedad', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('thumb', models.ImageField(upload_to='')),
                ('descripcion', models.TextField()),
                ('nHabitaciones', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '10+')], default=1)),
                ('nBanos', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '10+')], default=1)),
                ('superficie', models.FloatField(blank=True, null=True)),
                ('superficieConstruida', models.FloatField(blank=True, null=True)),
                ('ubicacion', models.CharField(max_length=50)),
                ('precio', models.CharField(max_length=10)),
                ('moneda', models.CharField(choices=[('UF', 'UF'), ('CLP', '$')], default='CLP', max_length=3)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('conserje', models.BooleanField(default=False)),
                ('logia', models.BooleanField(default=False)),
                ('amoblado', models.BooleanField(default=False)),
                ('estacionamiento', models.BooleanField(default=False)),
                ('nEstacionamientos', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '10+')], default=0)),
                ('piscina', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('comuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propiedades', to='manager.comunas', verbose_name='Comuna')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propiedades', to='manager.estadospropiedades', verbose_name='Estado')),
                ('operacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propiedades', to='manager.operacionespropiedades', verbose_name='Operación')),
                ('tipo_propiedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propiedades', to='manager.tipospropiedades', verbose_name='Tipo de propiedad')),
            ],
        ),
    ]
